name: PR build on master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: python3 setup.py sdist
