# Hourly build, cache not allowed
name: Nightly build on master

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      # Build
      - run: bash -x build.sh

      # Development Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          prerelease: true
          draft: false
          files: |
            build/*.deb

      # Upload QiNiu nightly
      - name: "Upload to QiNiu"
        env:
          QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
          QINIU_AK: ${{ secrets.QINIU_AK }}
          QINIU_SK: ${{ secrets.QINIU_SK }}
        run: |
          run: |
          sudo apt-get update
          sudo apt-get install -y unzip

          if [ $(uname -m) == 'x86_64' ]; then
            wget http://devtools.qiniu.com/qshell-linux-x64-v2.4.1.zip
            unzip qshell-linux-x64-v2.4.1.zip
            mv qshell-linux-x64-v2.4.1 qshell
          else
            wget http://devtools.qiniu.com/qshell-linux-x86-v2.4.1.zip
            unzip qshell-linux-x86-v2.4.1.zip
            mv qshell-linux-x86-v2.4.1 qshell
          fi
          chmod +x qshell
          ./qshell account -w ${QINIU_AK} ${QINIU_SK} deploy-account

          for f in $(find build -name '*.deb' ); do
            filename=${f##*/}
            key=nightly/${filename}
            ./qshell rput --overwrite ${QINIU_BUCKET} ${key} ${f}
          done
